### ISSUE TITLE
Detox: ECOMPROMISED error while running tests

### ISSUE THREAD

**Issue by cortisiko** [MetaMask/metamask-mobile#11097]
### What is this about?

We recently started noticing a new error that causes the iOS e2e tests to fail:
```
/Users/vagrant/git/node_modules/proper-lockfile/lib/lockfile.js:181
        onCompromised: (err) => { throw err; },
                                  ^
Error: Unable to update lock within the stale threshold
    at /Users/vagrant/git/node_modules/proper-lockfile/lib/lockfile.js:109:21
    at newFs.<computed> [as utimes] (/Users/vagrant/git/node_modules/proper-lockfile/lib/adapter.js:20:13)
    at Timeout._onTimeout (/Users/vagrant/git/node_modules/proper-lockfile/lib/lockfile.js:100:20)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7) {
  code: 'ECOMPROMISED'
}
```

The issue appears with detox, and a ticket has been opened [here](https://github.com/wix/Detox/issues/4210).
One suggestion in the ticket is to execute the `detox reset-lock-file` command before running the tests. This command seems effective when running tests against a release build but not against a debug build (which is how we run our tests).

We should first look into running the iOS tests on a QA/Release build

### Stakeholder review needed before the work gets merged

- [ ] Engineering (needed in most cases)
- [ ] Design
- [ ] Product
- [ ] QA (automation tests are required to pass before merging PRs but not all changes are covered by automation tests - please review if QA is needed beyond automation tests)
- [ ] Security
- [ ] Legal
- [ ] Marketing
- [ ] Management (please specify)
- [ ] Other (please specify)

**Comment by cortisiko** [comment]
This was addressed in https://github.com/MetaMask/metamask-mobile/pull/11186. If the issue still persists, we will reopen this task.
