### ISSUE TITLE
Can't open app after built it

### ISSUE THREAD

**Issue by mrbianchi** [MetaMask/metamask-mobile#1585]
**Describe the bug**
I followed the steps to build the app. After building it, the app crashes when opening in my phone.

**Screenshots**
![image](https://user-images.githubusercontent.com/25530181/82134901-30bfef00-97d3-11ea-81de-a213bdd8ce78.png)

**To Reproduce**
- $ yarn install
- $ yarn watch
- $ yarn start:android

**Expected behavior**
Open app normally

**Smartphone (please complete the following information):**
 - Device: Moto G 7 Plus
 - OS: Android
 - Version 10

**Comment by mrbianchi** [comment]
`05-17 19:06:08.534  7714  7714 D AndroidRuntime: Shutting down VM
05-17 19:06:08.535  7714  7714 E AndroidRuntime: FATAL EXCEPTION: main
05-17 19:06:08.535  7714  7714 E AndroidRuntime: Process: io.metamask, PID: 7714
05-17 19:06:08.535  7714  7714 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean org.json.JSONObject.getBoolean(java.lang.String)' on a null object reference
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at io.branch.rnbranch.RNBranchModule$1.onInitFinished(RNBranchModule.java:132)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at io.branch.referral.Branch.initializeSession(Branch.java:2582)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at io.branch.referral.Branch.initUserSessionInternal(Branch.java:1457)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at io.branch.referral.Branch.initSession(Branch.java:1053)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at io.branch.referral.Branch.initSession(Branch.java:1127)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at io.branch.rnbranch.RNBranchModule.initSession(RNBranchModule.java:118)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at io.metamask.MainActivity.onStart(MainActivity.java:34)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at android.app.Activity.performStart(Activity.java:7825)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
05-17 19:06:08.535  7714  7714 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
05-17 19:06:08.536  2104  2418 W ActivityTaskManager:   Force finishing activity io.metamask/.MainActivity
05-17 19:06:08.536  2104  7767 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
05-17 19:06:08.543  2104  2124 I ActivityManager: Showing crash dialog for package io.metamask u0
05-17 19:06:08.547  1855  1933 W EmuHWC2 : No layers, exit, buffer 0xed313380
`

**Comment by mrbianchi** [comment]
any help?
