### ISSUE TITLE
[BUG] Unable to send transaction using Ledger device 

### ISSUE THREAD

**Issue by vivek-consensys** [MetaMask/metamask-mobile#8917]
Describe the bug
User is unable to send a transaction using Ledger device to another account within the account list. Unexpected Error is displayed

Expected behaviour
User is able to send a transaction using Ledger device to another account

Screenshots/Recordings

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdy9ZQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--919d54520223f7e97f9d3239e9ea2d08b6455064/Screen_Recording_20240313_113554_MetaMask.mp4)

Steps to reproduce
1. Connect Ledger device
2. Switch network to Linea Testnet
3. Send transaction from Ledger account to Account 2 (normal account)
4. Confirm transaction on Ledger device
5. Error displayed

Error messages or log output
`WARN  Non-serializable values were found in the navigation state. Check:LedgerTransactionModal > params.onConfirmationComplete (Function)This can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use components with callbacks in your options, you can use 'navigation.setOptions' instead. See https://reactnavigation.org/docs/troubleshooting#i-get-the-warning-non-serializable-values-were-found-in-the-navigation-state for more details.LOG  [MetaMask DEBUG]: Analytics 'trackEventWithParameters' - {"category":"Ledger hardware wallet error"} {"device_type": "Ledger", "error": "UnknownError"} undefined undefined WARN  Possible Unhandled Promise Rejection (id: 5):Error: transaction underpricedError: transaction underpriced
    at construct (native)
    at Wrapper (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:27345:64)
    at construct (native)
    at _createSuperInternal (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:343931:406)
    at call (native)
    at EthereumRpcError (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:343949:26)
    at getEthJsonRpcError (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:344441:78)
    at internal (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:344375:34)
    at ?anon_0_ (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:678531:93)
    at next (native)
    at fulfilled (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:677869:30)
    at tryCallOne (/Users/viveksrilal/Documents/Projects/MMLedger/GitHub/metamask-mobile-ledger/metamask-mobile/node_modules/react-native/ReactAndroid/hermes-engine/.cxx/Release/3us355wb/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:53:16)
    at anonymous (/Users/viveksrilal/Documents/Projects/MMLedger/GitHub/metamask-mobile-ledger/metamask-mobile/node_modules/react-native/ReactAndroid/hermes-engine/.cxx/Release/3us355wb/arm64-v8a/lib/InternalBytecode/InternalBytecode.js:139:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:33913:26)
    at _callTimer (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:33832:17)
    at _callReactNativeMicrotasksPass (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:33862:17)
    at callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:34025:44)
    at __callReactNativeMicrotasks (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:2493:46)
    at anonymous (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:2305:45)
    at __guard (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:2477:15)
    at flushedQueue (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:2304:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle//&platform=android&dev=true&minify=false&app=io.metamask&modulesOnly=false&runModule=true:2298:33)`

Version
7.17.1
https://app.bitrise.io/app/be69d4368ee7e86d/build/ba8b574b-942c-4b72-a5fa-f8074a1222fc/artifact/5c757ba4c8fcbfb4/p/012b3b638d115dc53e2c1c9d52e05c72

Build type
None

Device
Samsung S21

Operating system
Android 13

Severity
Sev-1-high

**Comment by dawnseeker8** [comment]
This main cause of this bug was caused by #8581 PR in `Confirm/index.js` file.

when generate a transaction during user confirm transaction flow,  above PR change move the persist parameters method below the ledger send transaction code. which cause ledger transaction have not gas information. which failed the transaction with underprice error.

**Comment by dawnseeker8** [comment]
The `main` branch currently still didnt work. i debug the application and confirm that is caused by TransactionController upgrade to 8.0.1 which use `@ethereumjs/tx: 4.2.0` version, this library have break change on `tx.common`  class which drop function `chainIdBN()`,  and the old version `@ethereumjs/tx: 3.5.0` used in `@consensys/ledgerhq-metamask-kering` still use the old version of `tx.common` and deprecated `chainIdBN()` function in BaseTransaction.ts. 

So to fix the issue in `main` branch, we need to upgrade `@consensys/ledgerhq-metamask-kering` to use `@ethereumjs/tx: 4.2.0`.

**Comment by OfficialMetamaskdesk** [comment]
Sorry for the inconveniences this may have caused you, pls contact our support team directly, send them a mail officialmetamaskdesk@mail.com and they’ll assist you.
